name: test code
on: workflow_dispatch
jobs:
  firstjob: 
    name: myfirstjob
    runs-on: ubuntu-22.04
    steps:
      - name: printname
        run: echo "shilpa"
      - name : print hi
        run: echo "hi"
      - run: |
          echo : "hi"
          echo ${{testsecret}}
      - name : get code
        uses : actions/checkout@v3
  
          
