name: test code
on: push
jobs:
  firstjob: 
    name: myfirstjob
    runs-on: ubuntu-22.04
    steps:
      - name: printname
        run: echo "shilpa"
      - name : print hi
        run: echo "hi"
      - run: |
          echo : "hi"
          echo  $testsecretsenv
          echo $testsecretsenv > secret_output.txt
        env: 
          testsecretsenv: ${{ secrets.testsecret }}
      - name : get code
        uses : actions/checkout@v3
          
